export enum SectionType {
  IDENTIFICATION = 'IDENTIFICATION',
  CONSULTATION_REASON = 'CONSULTATION_REASON',
  BACKGROUND = 'BACKGROUND',
  PROCEDURE_TESTS = 'PROCEDURE_TESTS',
  OBSERVED_BEHAVIOR = 'OBSERVED_BEHAVIOR',
  QUESTIONNAIRE_SYMPTOMS = 'QUESTIONNAIRE_SYMPTOMS',
  COGNITIVE_EVALUATION = 'COGNITIVE_EVALUATION',
  SOCIAL_COGNITION = 'SOCIAL_COGNITION',
  RESULTS_SYNTHESIS = 'RESULTS_SYNTHESIS',
  CONCLUSIONS = 'CONCLUSIONS',
  RECOMMENDATIONS = 'RECOMMENDATIONS',
  ANNEXES = 'ANNEXES',
}

export enum SectionStatus {
  PENDING = 'PENDING',
  AI_GENERATED = 'AI_GENERATED',
  CLINICIAN_REVIEWING = 'CLINICIAN_REVIEWING',
  APPROVED = 'APPROVED',
}

export enum GeneratedBy {
  HUMAN = 'HUMAN',
  AI = 'AI',
  RULES = 'RULES',
}

export const AI_GENERATED_SECTIONS: SectionType[] = [
  SectionType.BACKGROUND,
  SectionType.OBSERVED_BEHAVIOR,
];
