import { PrismaClient } from '@prisma/client';

type DictEntry = {
  code: string;
  category: string;
  content: string;
};

const ENTRIES: DictEntry[] = [
  // ── WISC-V — ICV
  { code: 'WISC5.ICV.muy_alto', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) de {{paciente}} se ubica en el rango Muy alto (SS = {{puntaje}}; Pc {{percentil}}), evidenciando un desarrollo destacado de las habilidades verbales. Muestra una sólida capacidad para comprender y expresar conceptos verbales complejos, razonar con el lenguaje y evocar conocimiento adquirido.' },
  { code: 'WISC5.ICV.superior', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando habilidades verbales bien desarrolladas que superan a la mayoría de sus pares. Destaca en la comprensión del lenguaje, el razonamiento verbal y la expresión de conceptos.' },
  { code: 'WISC5.ICV.medio_alto', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Medio alto (SS = {{puntaje}}; Pc {{percentil}}), indicando habilidades verbales por sobre el promedio. La comprensión del lenguaje, el razonamiento verbal y el vocabulario se encuentran adecuadamente desarrollados.' },
  { code: 'WISC5.ICV.medio', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Medio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado para su edad. La comprensión del lenguaje oral, el razonamiento verbal y el manejo del vocabulario se encuentran dentro de los parámetros normativos.' },
  { code: 'WISC5.ICV.medio_bajo', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Medio bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando un desarrollo de las habilidades verbales por debajo del promedio esperado para su edad. Se observan dificultades relativas en la comprensión del lenguaje, el razonamiento verbal y/o la expresión de conceptos.' },
  { code: 'WISC5.ICV.limitrofe', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), indicando un desarrollo verbal significativamente inferior al esperado. Las habilidades de comprensión del lenguaje, razonamiento verbal y vocabulario se encuentran considerablemente disminuidas respecto a su grupo de referencia.' },
  { code: 'WISC5.ICV.extremadamente_bajo', category: 'WISC5_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Extremadamente bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando un desarrollo verbal muy por debajo del esperado para su edad. Las habilidades de comprensión del lenguaje, razonamiento verbal y expresión conceptual presentan compromisos significativos que requieren atención especializada.' },

  // ── WISC-V — IVE
  { code: 'WISC5.IVE.muy_alto', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se ubica en el rango Muy alto (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una capacidad sobresaliente para analizar, sintetizar y reproducir información visual y espacial. El procesamiento visoperceptivo y la organización espacial son fortalezas destacadas.' },
  { code: 'WISC5.IVE.superior', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando habilidades visoespaciales bien por sobre el promedio. Muestra adecuada capacidad para analizar relaciones espaciales y reproducir configuraciones visuales complejas.' },
  { code: 'WISC5.IVE.medio_alto', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se ubica en el rango Medio alto (SS = {{puntaje}}; Pc {{percentil}}), indicando habilidades visoespaciales sobre el promedio esperado para su edad.' },
  { code: 'WISC5.IVE.medio', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se sitúa en el rango Medio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado para su edad. El análisis visoespacial y la construcción de figuras a partir de modelos se encuentran dentro de parámetros normativos.' },
  { code: 'WISC5.IVE.medio_bajo', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se ubica en el rango Medio bajo (SS = {{puntaje}}; Pc {{percentil}}), indicando dificultades relativas en el procesamiento visoespacial. Se observan limitaciones en el análisis de relaciones espaciales y/o la reproducción de configuraciones visuales.' },
  { code: 'WISC5.IVE.limitrofe', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en el procesamiento visoespacial que se alejan considerablemente del promedio esperado para su edad.' },
  { code: 'WISC5.IVE.extremadamente_bajo', category: 'WISC5_INDICES', content: 'El Índice Visuoespacial (IVE) se ubica en el rango Extremadamente bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en el análisis y procesamiento visoespacial que requieren evaluación e intervención especializada.' },

  // ── WISC-V — MRT
  { code: 'WISC5.MRT.muy_alto', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se ubica en el rango Muy alto (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una capacidad sobresaliente para retener, manipular y operar con información en la memoria de trabajo. Esta constituye una fortaleza cognitiva significativa.' },
  { code: 'WISC5.MRT.superior', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando una capacidad bien desarrollada para mantener y manipular información de forma activa.' },
  { code: 'WISC5.MRT.medio_alto', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se ubica en el rango Medio alto (SS = {{puntaje}}; Pc {{percentil}}), indicando una capacidad por sobre el promedio para retener y operar con información de forma simultánea.' },
  { code: 'WISC5.MRT.medio', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se sitúa en el rango Medio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado para su edad. La capacidad para mantener y manipular información activamente se encuentra dentro de parámetros normativos.' },
  { code: 'WISC5.MRT.medio_bajo', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se ubica en el rango Medio bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando limitaciones en la capacidad para retener y operar con información de forma activa. Esto puede impactar el seguimiento de instrucciones complejas y el aprendizaje que requiere procesamiento simultáneo.' },
  { code: 'WISC5.MRT.limitrofe', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en la capacidad de retención y manipulación activa de información, con impacto probable en el funcionamiento académico y cotidiano.' },
  { code: 'WISC5.MRT.extremadamente_bajo', category: 'WISC5_INDICES', content: 'El Índice de Memoria de Trabajo (MRT) se ubica en el rango Extremadamente bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en la memoria de trabajo que afectan de manera importante la capacidad de aprendizaje y el funcionamiento ejecutivo general.' },

  // ── WISC-V — IRP
  { code: 'WISC5.IRP.muy_alto', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se ubica en el rango Muy alto (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una capacidad sobresaliente para identificar patrones, razonar inductivamente y resolver problemas novedosos sin apoyo del conocimiento previo.' },
  { code: 'WISC5.IRP.superior', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando una capacidad bien desarrollada para el razonamiento lógico-abstracto y la resolución de problemas novedosos.' },
  { code: 'WISC5.IRP.medio_alto', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se ubica en el rango Medio alto (SS = {{puntaje}}; Pc {{percentil}}), indicando una capacidad de razonamiento abstracto y resolución de problemas por sobre el promedio.' },
  { code: 'WISC5.IRP.medio', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se sitúa en el rango Medio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado para su edad. La capacidad para identificar relaciones, razonar inductivamente y resolver problemas nuevos se encuentra dentro de parámetros normativos.' },
  { code: 'WISC5.IRP.medio_bajo', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se ubica en el rango Medio bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando dificultades relativas en el razonamiento abstracto y la resolución de problemas novedosos, por debajo de lo esperado para su edad.' },
  { code: 'WISC5.IRP.limitrofe', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en la capacidad de razonamiento lógico-abstracto e inductivo.' },
  { code: 'WISC5.IRP.extremadamente_bajo', category: 'WISC5_INDICES', content: 'El Índice de Razonamiento Fluido (IRP) se ubica en el rango Extremadamente bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en el razonamiento abstracto y fluido que impactan de manera importante en la capacidad de resolución de problemas.' },

  // ── WISC-V — IVP
  { code: 'WISC5.IVP.muy_alto', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se ubica en el rango Muy alto (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad sobresaliente para procesar información visual simple de forma rápida y eficiente.' },
  { code: 'WISC5.IVP.superior', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando una velocidad de procesamiento visomotor bien desarrollada.' },
  { code: 'WISC5.IVP.medio_alto', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se ubica en el rango Medio alto (SS = {{puntaje}}; Pc {{percentil}}), indicando una velocidad de procesamiento de información visual por sobre el promedio esperado.' },
  { code: 'WISC5.IVP.medio', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se sitúa en el rango Medio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado para su edad. La velocidad para escanear, identificar y ejecutar tareas visuales simples se encuentra dentro de parámetros normativos.' },
  { code: 'WISC5.IVP.medio_bajo', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se ubica en el rango Medio bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad de procesamiento de información visual y motora por debajo del promedio, lo que puede impactar el rendimiento en tareas que requieren rapidez y eficiencia.' },
  { code: 'WISC5.IVP.limitrofe', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en la velocidad con que procesa y responde ante información visual simple.' },
  { code: 'WISC5.IVP.extremadamente_bajo', category: 'WISC5_INDICES', content: 'El Índice de Velocidad de Procesamiento (IVP) se ubica en el rango Extremadamente bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad de procesamiento muy lenta que impacta de manera transversal el rendimiento cognitivo general.' },

  // ── WAIS-IV — ICV
  { code: 'WAIS4.ICV.muy_superior', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) de {{paciente}} se ubica en el rango Muy superior (SS = {{puntaje}}; Pc {{percentil}}), evidenciando un desarrollo sobresaliente de las habilidades verbales. Muestra una sólida capacidad para razonar con el lenguaje, comprender conceptos abstractos y evocar conocimiento cristalizado.' },
  { code: 'WAIS4.ICV.superior', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando habilidades verbales bien desarrolladas que superan a la mayoría de sus pares. Destaca en comprensión del lenguaje, razonamiento verbal y vocabulario.' },
  { code: 'WAIS4.ICV.alto', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Alto (SS = {{puntaje}}; Pc {{percentil}}), indicando habilidades verbales por sobre el promedio. La comprensión del lenguaje oral, el razonamiento verbal y el manejo del vocabulario están bien desarrollados.' },
  { code: 'WAIS4.ICV.promedio', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Promedio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado. La comprensión del lenguaje, el razonamiento verbal y el vocabulario se encuentran dentro de parámetros normativos.' },
  { code: 'WAIS4.ICV.bajo_promedio', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Bajo el promedio (SS = {{puntaje}}; Pc {{percentil}}), evidenciando un rendimiento verbal inferior al esperado. Se observan dificultades relativas en la comprensión del lenguaje, el razonamiento verbal y/o la expresión de conceptos.' },
  { code: 'WAIS4.ICV.limitrofe', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), indicando compromisos significativos en las habilidades verbales que se alejan considerablemente del promedio.' },
  { code: 'WAIS4.ICV.muy_bajo', category: 'WAIS4_INDICES', content: 'El Índice de Comprensión Verbal (ICV) se ubica en el rango Muy bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en las habilidades verbales, incluyendo comprensión del lenguaje, razonamiento verbal y vocabulario.' },

  // ── WAIS-IV — IRP
  { code: 'WAIS4.IRP.muy_superior', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se ubica en el rango Muy superior (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una capacidad sobresaliente para analizar información visual, identificar relaciones espaciales y resolver problemas no verbales de manera eficiente.' },
  { code: 'WAIS4.IRP.superior', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando habilidades visoperceptivas y de razonamiento no verbal bien por sobre el promedio.' },
  { code: 'WAIS4.IRP.alto', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se ubica en el rango Alto (SS = {{puntaje}}; Pc {{percentil}}), indicando habilidades de razonamiento visoespacial y perceptivo por sobre el promedio esperado.' },
  { code: 'WAIS4.IRP.promedio', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se sitúa en el rango Promedio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado. La capacidad para analizar información visual y resolver problemas no verbales se encuentra dentro de parámetros normativos.' },
  { code: 'WAIS4.IRP.bajo_promedio', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se ubica en el rango Bajo el promedio (SS = {{puntaje}}; Pc {{percentil}}), evidenciando dificultades relativas en el razonamiento visoperceptivo y la resolución de problemas no verbales.' },
  { code: 'WAIS4.IRP.limitrofe', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en el razonamiento visoperceptivo y espacial.' },
  { code: 'WAIS4.IRP.muy_bajo', category: 'WAIS4_INDICES', content: 'El Índice de Razonamiento Perceptual (IRP) se ubica en el rango Muy bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en la capacidad de razonamiento visoperceptivo y espacial.' },

  // ── WAIS-IV — MT
  { code: 'WAIS4.MT.muy_superior', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se ubica en el rango Muy superior (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una capacidad sobresaliente para mantener y manipular activamente información en la memoria de corto plazo.' },
  { code: 'WAIS4.MT.superior', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando una capacidad bien desarrollada para retener y operar con información de forma activa.' },
  { code: 'WAIS4.MT.alto', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se ubica en el rango Alto (SS = {{puntaje}}; Pc {{percentil}}), indicando una capacidad por sobre el promedio para mantener y manipular información simultáneamente.' },
  { code: 'WAIS4.MT.promedio', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se sitúa en el rango Promedio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado. La capacidad para mantener y operar con información de forma activa se encuentra dentro de parámetros normativos.' },
  { code: 'WAIS4.MT.bajo_promedio', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se ubica en el rango Bajo el promedio (SS = {{puntaje}}; Pc {{percentil}}), evidenciando limitaciones en la capacidad de retención y manipulación activa de información, con posible impacto en tareas que requieren procesamiento simultáneo.' },
  { code: 'WAIS4.MT.limitrofe', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en la memoria de trabajo con impacto probable en el funcionamiento ejecutivo y el aprendizaje.' },
  { code: 'WAIS4.MT.muy_bajo', category: 'WAIS4_INDICES', content: 'El Índice de Memoria de Trabajo (MT) se ubica en el rango Muy bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos severos en la capacidad de retención y manipulación activa de información.' },

  // ── WAIS-IV — VP
  { code: 'WAIS4.VP.muy_superior', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se ubica en el rango Muy superior (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad sobresaliente para procesar y responder ante información visual simple de manera rápida y precisa.' },
  { code: 'WAIS4.VP.superior', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se sitúa en el rango Superior (SS = {{puntaje}}; Pc {{percentil}}), reflejando una velocidad de procesamiento visomotor bien desarrollada.' },
  { code: 'WAIS4.VP.alto', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se ubica en el rango Alto (SS = {{puntaje}}; Pc {{percentil}}), indicando una velocidad de procesamiento de información visual por sobre el promedio esperado.' },
  { code: 'WAIS4.VP.promedio', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se sitúa en el rango Promedio (SS = {{puntaje}}; Pc {{percentil}}), acorde al nivel esperado. La velocidad para escanear, identificar y ejecutar tareas visuales simples se encuentra dentro de parámetros normativos.' },
  { code: 'WAIS4.VP.bajo_promedio', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se ubica en el rango Bajo el promedio (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad de procesamiento de información visual y motora por debajo del promedio, lo que puede afectar el rendimiento en tareas que requieren rapidez y eficiencia.' },
  { code: 'WAIS4.VP.limitrofe', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se sitúa en el rango Limítrofe (SS = {{puntaje}}; Pc {{percentil}}), evidenciando compromisos significativos en la velocidad de procesamiento visomotor.' },
  { code: 'WAIS4.VP.muy_bajo', category: 'WAIS4_INDICES', content: 'El Índice de Velocidad de Procesamiento (VP) se ubica en el rango Muy bajo (SS = {{puntaje}}; Pc {{percentil}}), evidenciando una velocidad de procesamiento muy lenta que impacta de manera transversal el rendimiento cognitivo.' },

  // ── Síntesis
  { code: 'SINTESIS.SNP_CHC.base', category: 'SINTESIS', content: 'En síntesis, el perfil cognitivo de {{paciente}} muestra {{dominios_afectados}}. Los resultados deben interpretarse en el contexto del desarrollo integral del/la evaluado/a y los antecedentes clínicos relevantes.' },
  { code: 'SINTESIS.ESTANDAR.base', category: 'SINTESIS', content: 'En síntesis, la evaluación neuropsicológica de {{paciente}} evidencia {{dominios_afectados}}. Los hallazgos deben integrarse con la información clínica, conductual y contextual para una comprensión integral del funcionamiento cognitivo.' },
];

export async function seedClinicalDictionaries(prisma: PrismaClient) {
  for (const entry of ENTRIES) {
    await prisma.clinicalDictionary.upsert({
      where: { code: entry.code },
      update: { content: entry.content, category: entry.category },
      create: { code: entry.code, category: entry.category, content: entry.content },
    });
  }
  console.log(`✓ Clinical dictionaries seeded (${ENTRIES.length} entradas)`);
}
